name: Maven Package Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'maven'

      - name: Maven build
        run: mvn --file pom.xml package

  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'maven'

      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: mvn --settings settings.xml --file pom.xml deploy